name: morpheme_http
description: Future-based library for making HTTP requests modified from http package.
version: 1.2.1
homepage: https://morpheme.design/
repository: https://github.com/morphemedesign/morpheme-flutter-library/tree/main/packages/morpheme_http

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  uuid: ^4.4.0
  equatable: ^2.0.5
  logger: ^2.3.0
  hive: ^2.2.3
  path_provider: ^2.1.3

  morpheme_inspector: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
